name:                arbitrary-adt-example
version:             0.1.0.0
github:              plow-technologies/hspec-golden-cereal
license:             BSD3
author:              James M.C. Haver II
maintainer:          bruno-cadorette@plowtech.net
copyright:           BSD3

extra-source-files:
- README.md
- ChangeLog.md
synopsis:            hspec-golden-cereal example
description:         Please see the README on Github at <https://github.com/plow-technologies/hspec-golden-cereal#readme>

dependencies:
- base >= 4.7 && < 5
- cereal
- QuickCheck
- quickcheck-arbitrary-adt
- hspec-golden-cereal


library:
  source-dirs: src

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arbitrary-adt-example
